version: '3'

vars:
  PROJECT_NAME: banana-lab-gcp-wp-pulumi-play
tasks:
  deps:
    desc: "Download and verify module dependencies."
    status: ["none"]
    cmds:
      - go mod tidy
      - go mod verify
